import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1712770070072 implements MigrationInterface {
    name = 'Migration1712770070072'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` DROP FOREIGN KEY \`FK_ef0bd07b0e201194eae3ad9d198\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba8cef5776e910f9f053ec5ec6\` ON \`jobs\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`job_key\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`target\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`executed_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`completed_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`inventory_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD UNIQUE INDEX \`IDX_9276e660e331f9cf1056edabab\` (\`inventory_id\`)`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`job_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`jobs\` CHANGE \`status\` \`status\` enum ('pending', 'processing', 'completed', 'failed', 'canceled') NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`DROP INDEX \`REL_ef0bd07b0e201194eae3ad9d19\` ON \`sku_inventories\``);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` ADD \`sku\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` ADD UNIQUE INDEX \`IDX_ef0bd07b0e201194eae3ad9d19\` (\`sku\`)`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_35e763f0306bc67f204cc32612\` ON \`jobs\` (\`target\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_ef0bd07b0e201194eae3ad9d19\` ON \`sku_inventories\` (\`sku\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8badff639dc38caa167866e4a8\` ON \`product_skus\` (\`sellable\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_9276e660e331f9cf1056edabab\` ON \`product_skus\` (\`inventory_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_20c984fa6b83cfba4b4a1e5211\` ON \`products\` (\`product_status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_142f50b13855b5740d20a71eab\` ON \`inventory_entities\` (\`status\`)`);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` ADD CONSTRAINT \`FK_ef0bd07b0e201194eae3ad9d198\` FOREIGN KEY (\`sku\`) REFERENCES \`product_skus\`(\`sku\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD CONSTRAINT \`FK_9276e660e331f9cf1056edabab1\` FOREIGN KEY (\`inventory_id\`) REFERENCES \`sku_inventories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD CONSTRAINT \`FK_acd00c9e50cc3328e5f7676377f\` FOREIGN KEY (\`job_id\`) REFERENCES \`jobs\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP FOREIGN KEY \`FK_acd00c9e50cc3328e5f7676377f\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP FOREIGN KEY \`FK_9276e660e331f9cf1056edabab1\``);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` DROP FOREIGN KEY \`FK_ef0bd07b0e201194eae3ad9d198\``);
        await queryRunner.query(`DROP INDEX \`IDX_142f50b13855b5740d20a71eab\` ON \`inventory_entities\``);
        await queryRunner.query(`DROP INDEX \`IDX_20c984fa6b83cfba4b4a1e5211\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`REL_9276e660e331f9cf1056edabab\` ON \`product_skus\``);
        await queryRunner.query(`DROP INDEX \`IDX_8badff639dc38caa167866e4a8\` ON \`product_skus\``);
        await queryRunner.query(`DROP INDEX \`REL_ef0bd07b0e201194eae3ad9d19\` ON \`sku_inventories\``);
        await queryRunner.query(`DROP INDEX \`IDX_35e763f0306bc67f204cc32612\` ON \`jobs\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` DROP INDEX \`IDX_ef0bd07b0e201194eae3ad9d19\``);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` ADD \`sku\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_ef0bd07b0e201194eae3ad9d19\` ON \`sku_inventories\` (\`sku\`)`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attributes\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_options\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`seo_infos\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`jobs\` CHANGE \`status\` \`status\` enum ('pending', 'processing', 'completed', 'failed') NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`inventory_entities\` DROP COLUMN \`job_id\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP INDEX \`IDX_9276e660e331f9cf1056edabab\``);
        await queryRunner.query(`ALTER TABLE \`product_skus\` DROP COLUMN \`inventory_id\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`completed_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`executed_at\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` DROP COLUMN \`target\``);
        await queryRunner.query(`ALTER TABLE \`jobs\` ADD \`job_key\` varchar(255) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_ba8cef5776e910f9f053ec5ec6\` ON \`jobs\` (\`job_key\`)`);
        await queryRunner.query(`ALTER TABLE \`sku_inventories\` ADD CONSTRAINT \`FK_ef0bd07b0e201194eae3ad9d198\` FOREIGN KEY (\`sku\`) REFERENCES \`sku_inventories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
