import AntdProvider from '@/providers/AntdProvider';
import { CounterProvider } from '@/providers/CounterProvider';
import EmotionProvider from '@/providers/EmotionProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  header,
  footer,
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmotionProvider>
          <AntdProvider>
            <CounterProvider>
              {header}
              {children}
              {footer}
            </CounterProvider>
          </AntdProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
