import type { Metadata } from 'next';
import './global.css';
import React from 'react';
import { AuthProvider } from '@/modules/auth/AuthProvider';
import { AppLayoutProvider } from '@/modules/layout/providers';
import { AppFooter, AppHeader } from '@/modules/layout/containers';
import { MainContent } from '@/modules/layout/components';

import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Hello App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${poppins.variable}`} suppressHydrationWarning>
      <body>
        <AppLayoutProvider>
          <AuthProvider>
            <AppHeader />
            <MainContent>{children}</MainContent>
            <AppFooter />
          </AuthProvider>
        </AppLayoutProvider>
      </body>
    </html>
  );
}
